#install.packages("infotheo")
library(infotheo)

X=c(4,3,4,3,4,3,4)
Y=c(1,4,6,2,7,9,8)
entropy(X)
entropy(Y)
mutinformation(X,Y)
plot(X,Y, ylim = c(0,10),xlim = c(0,10),pch=19)
#install.packages("eulerr")
library(eulerr)
fit <- euler(c(A = entropy(X), B = entropy(Y), "A&B" = mutinformation(X,Y)))
plot(fit)
